---
- name: install java on ubuntu 
  hosts: ubuntu
  become: yes
  tasks:
   - name: update packages and install ubuntu
     ansible.builtin.apt:
       name: "{{ java_package }}"
       update_cache: yes
       state: present
   - name: create a group tomcat
     ansible.builtin.group:
       name: "{{ group_package }}"
       state: present
   - name: create user tomcat
     ansible.builtin.user:
       name: "{{ user_package }}"
       create_home: true
       group: "{{ group_package }}"
       home: "{{ home_dir }}"
       shell: "{{ default_shell }}"
       state: present
   - name: downloading tomcat on ubuntu
     ansible.builtin.get_url:
       url: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
       dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
     
      # "this is tomcat downloading Link:- wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.14/bin/apache-tomcat-10.1.25.tar.gz -P /tmp"