---
- name: install java on ubuntu 
  hosts: all
  become: yes
  tasks:
   - name: update packages and install ubuntu
     ansible.builtin.apt:
       name: openjdk-11-jdk
       update_cache: yes
       state: present
   - name: create a group
     ansible.builtin.group:
       name: tomact
       state: present
   - name: create user tomcat
     ansible.builtin.user:
       name: Tomcat
       create_home: true
       group: tomcat
       home: /opt/tomcat
       shell: /bin/false